-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

local map = vim.keymap.set

-- バッファ操作（bufferline.nvim）
map("n", "<Tab>", "<Cmd>BufferLineCycleNext<CR>", { silent = true, desc = "次のバッファへ" })
map("n", "<S-Tab>", "<Cmd>BufferLineCyclePrev<CR>", { silent = true, desc = "前のバッファへ" })
for i = 1, 9 do
  map("n", "<leader>" .. i, "<Cmd>BufferLineGoToBuffer " .. i .. "<CR>", { silent = true, desc = "バッファ" .. i .. "へ" })
end
map("n", "<leader>x", function()
  Snacks.bufdelete()
end, { silent = true, desc = "バッファを閉じる" })
map("n", "<leader>X", function()
  Snacks.bufdelete({ force = true })
end, { silent = true, desc = "バッファを強制的に閉じる" })
map("n", "<leader>p", "<Cmd>BufferLineTogglePin<CR>", { silent = true, desc = "バッファをピン留め" })
map("n", "<leader>bh", "<Cmd>BufferLineMovePrev<CR>", { silent = true, desc = "バッファを左に移動" })
map("n", "<leader>bl", "<Cmd>BufferLineMoveNext<CR>", { silent = true, desc = "バッファを右に移動" })

-- Snacks Picker
map("n", ",<cr>", function()
  Snacks.picker.picker_actions()
end, { desc = "Picker Actions" })
map("n", ",<space>", function()
  Snacks.picker.grep({ hidden = true })
end, { desc = "Grep" })
map("n", ",b", function()
  Snacks.picker.grep_buffers()
end, { desc = "Grep Buffers" })
map({ "n", "x" }, ",s", function()
  Snacks.picker.grep_word()
end, { desc = "Grep String" })
map("n", ",P", function()
  Snacks.picker.projects()
end, { desc = "Projects" })
map("n", ",B", function()
  Snacks.picker.buffers()
end, { desc = "Buffers" })
map("n", ",c", function()
  Snacks.picker.colorschemes()
end, { desc = "Colorscheme" })
map("n", ",f", function()
  Snacks.picker.files({ hidden = true })
end, { desc = "Find Files" })
map("n", ",g", function()
  Snacks.picker.git_branches()
end, { desc = "Git Branches" })
map("n", ",h", function()
  Snacks.picker.help()
end, { desc = "Help Pages" })
map("n", ",j", function()
  Snacks.picker.jumps()
end, { desc = "Jumplist" })
map("n", ",l", function()
  Snacks.picker.lazy()
end, { desc = "Lazy" })
map("n", ",m", function()
  Snacks.picker.marks()
end, { desc = "Marks" })
map("n", ",p", function()
  Snacks.picker.commands()
end, { desc = "Commands" })
map("n", ",q", function()
  Snacks.picker.qflist()
end, { desc = "Quickfix List" })
map("n", ",r", function()
  Snacks.picker.resume()
end, { desc = "Resume" })
map("n", ",t", function()
  Snacks.picker.todo_comments()
end, { desc = "TODO" })
map("n", ",i", function()
  Snacks.picker.icons()
end, { desc = "Icons" })
map("n", ",z", function()
  Snacks.picker.zoxide()
end, { desc = "Zoxide" })
map("n", ",d", function()
  Snacks.picker.diagnostics_buffer()
end, { desc = "Buffer Diagnostics" })
map("n", ",D", function()
  Snacks.picker.diagnostics()
end, { desc = "Diagnostics" })

-- LSP
map("n", "<leader>rn", vim.lsp.buf.rename, { desc = "Rename" })

-- ファイル検索
map("n", "<C-p>", function()
  Snacks.picker.files()
end, { desc = "Find Files" })
